name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          TAG="sha-${GITHUB_SHA::8}"
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:$TAG"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

  deploy:
    name: Deploy to Minikube
    runs-on: [self-hosted, wisecow]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load image into Minikube
        run: |
          TAG="sha-${GITHUB_SHA::8}"
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:$TAG"
          echo "Loading $IMAGE into Minikube..."
          minikube image load "$IMAGE"

      - name: Start minikube
        run: |
          minikube start
          
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8/

      - name: Update deployment image
        run: |
          TAG="sha-${GITHUB_SHA::8}"
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:$TAG"
          kubectl set image deployment/wisecow-deployment wisecow-container="$IMAGE" --record

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/wisecow-deployment --timeout=120s
