name: CI-CD

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v4
    
    - name: Set up Docker 
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:${GITHUB_SHA::8} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:${GITHUB_SHA::8}

  deploy:
    name: Deploy to Minikube
    runs-on: [self-hosted, wisecow]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load latest image into Minikube
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:${GITHUB_SHA::8}
          echo "Loading $IMAGE into Minikube..."
          minikube image load $IMAGE

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8/
  
      - name: Update deployment image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wisecow-app:${GITHUB_SHA::8}
          kubectl set image deployment/wisecow-deployment wisecow-container=$IMAGE --record
  
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/wisecow-deployment --timeout=120s
      
